version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postrgres
      - POSTGRES_USER=postrgres
      - POSTGRES_DB=mgpDB
    volumes:
      - ./database:/var/lib/postgresql/data