version: '3'
services:
  app:
    build: .
    ports:
      - "80:8080"
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mgpDB
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: always