server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/mgpDB
    url: jdbc:postgresql://postgres:5432/mgpDB
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
#  web:
#    resources:
#      cache:
#        cachecontrol:
#          max-age: 365d